### ISSUE TITLE
Custom numeric rules, default value and an idea

### ISSUE THREAD

**Issue by Globegitter** [Josebaseba/sails-hook-validator#1]
First of all, it is great to see an addon like this thanks!

From my use-cases I have seen it would be nice if I was able to send a custom error message back to the client. I love the fact that you have auto-message, that allows for quick prototyping, but maybe you could have a setting to turn it off, or if you wrap it in a `try/catch` statement it catches the error instead of sending the message.

Edit: Sorry, scrap the custom messages just saw that in the Readme. Proper reading can be beneficial sometimes ;)
Having said that it might be nice to return a default error message as json with the error code in it.

Also I think it would be really useful to have custom rules for int/numeric, such as `int, larger than 0` or `int larger than 10 smaller than 100`. With the current syntax that could either be expressed via `['int', 0, 100], where-as the first number is the minimum. Or ['int', '>0', '<10'] to make the syntax a bit more explicit.

It would be great to have the option for a default value. So if a parameter is not given at all it takes that default parameter. Not sure yet what the best syntax for that would be, but let me know what you think, would love to throw some ideas around.

Also another idea I was thinking about to make the syntax a bit more expressive: Something like

``` js
req.validator({
  id: isInt(min,max)
  email: isEmail().toLower()
});
//or if it is just one
req.validator('id').isString('custom regular expression').toLower();
```

Not sure right now how that would be possible from a programmatic point of view and just an idea because I usually thing syntax that read like english is the most intuitive. Let me know what you think.

Also I would love to make a PR for any of these ideas but a bit too busy at the moment. In any case, thanks again and feel free to ignore the last bit ;)

**Comment by Josebaseba** [comment]
Hey!

Feel free to collaborate with all the pull requests that you want. I think that this syntax: 

``` javascript
  req.validator({
      url: ['url', 'toLower'],
      creditCard: 'creditCard'
  });
```

Is pretty clear, and maybe your idea is a really big change looking at the programatic point right now. For now I'll leave it this way but I repeat that I'm open to any pull request.

In the other hand, the default values and the custom rules can be really useful... Maybe something like this(?):

``` javascript
    req.validator({
       url: ['url', 'toLower'],
       creditCard: 'creditCard',
       age: {
           type: 'int',
           max: 99,
           min: 1,
           default: 18
       }
    });
```

That will be really similar to the Waterline models structure and it should be easy to implement.

I'm pretty busy right now but I'll try to end the docs and keep improving this hooks because is so useful in my daily work. The controllers code become much more cleaner this way. Check the test to see how it works with more details :+1: 

Any help is welcome! Thanks!

**Comment by Globegitter** [comment]
@Josebaseba Yeah you are right it is a pretty clean syntax and I suppose I am just a fan of english syntax. But yeah I love what you proposed for custom rules and default. That would really help a lot :)

Yeah quite busy myself right now fixing up libraries on my critical path. If I find some spare time or it gets onto my critical path I'll submit a PR - thanks :)
